### ISSUE TITLE
[Bug] Not all image sizes are pulled

### ISSUE THREAD

**Issue by EKami** [Fried-Chicken/ghost-static-site-generator#37]
In one theme that I use I have an image of size `w1140` stored in `/content/images/size/w1140/2021/02/nodes-1.png` but when I use gssg the only sizes that are being pulled are:
```
$ ls content/images/size/
w1000  w150  w600  w750  w960
```
It seems the sizes above `w1000` are ignored. It's easy to replicate. One can use the theme "Dawn" available [here](https://ghost.org/marketplace/) then create a post in Ghost and in "post settings" change the post image (and use a large enough image).

**Comment by mvolpato** [comment]
I do get all the folders:

```
$ ls public/content/images/size
w1000 w1140 w1600 w400  w600  w750  w960
```

but some images are missing from the bigger folders.

**Comment by beardsleym** [comment]
Same problem, ended up manually copying `content/images` folder into `static/content/images`

**Comment by Fried-Chicken** [comment]
Hi @lukefaccin, I've merged your PR but I did some housekeeping as well, please can you test the new version `v1.1.2` to see if it fixes your issue. Thanks

**Comment by rodriguezsergio** [comment]
It looks like this bug is still present. I'm missing the `w1920` folder locally.

Using version `1.1.4`.

**Comment by lukefaccin** [comment]
@rodriguezsergio, did you try the `--saveAsReferer` flag from the [readme](https://github.com/Fried-Chicken/ghost-static-site-generator/blob/master/README.md#save-redirected-assets-as-referer-path)? Mine isn't generating a `w1920` folder but it does generate other numbered folders successfully which were previously failing. Hope this helps 🤞
